complete-module-3
js-tasks-ru/jsbasic-20240115_sharavaya pull request #4
Opened 2024-02-01 00:27 UTC by GeorgeAlexeev

array/method/func

2024-02-01 00:28 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-01 10:32 UTC, SinimaWath requested changes

2024-02-01 10:32 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return newArr;
Давай тут заиспользуем `arr.filter`

2024-02-01 10:32 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  }
Давай тут заиспользуем map

2024-02-01 15:37 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-01 15:39 UTC, GeorgeAlexeev commented on 3-module/5-task/index.js
> +  }
Методом тысячи переборов пришел к выводу, что map довольно умная штука, понимающая "с полуслова", но из-за этого очень сложная

2024-02-01 15:40 UTC, GeorgeAlexeev commented on 3-module/2-task/index.js
> +  return newArr;
Делал через цикл, потому что был уверен, что filter сделает мне новый массив (не знаю, просто был уверен xD )

2024-02-03 17:43 UTC, SinimaWath approved these changes
Все круто!

2024-02-03 17:43 UTC, merged