module5/petProject_1
js-tasks-ru/jsbasic-20240115_sharavaya pull request #6
Opened 2024-02-10 18:33 UTC by GeorgeAlexeev

event/slider/func
Есть один нюанс, указал в комментариях к проектному заданию.

2024-02-11 15:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-11 15:37 UTC, SinimaWath requested changes

2024-02-11 15:37 UTC, SinimaWath commented on 5-module/2-task/index.js
> +// Почему он не указан в статье "Атрибуты и свойства" на уровне с set/has/remove/get ?
Потому что он не очень полезный, кмк.

`text.hidden = !text.hidden` достаточно легко решает задачу

2024-02-11 15:37 UTC, SinimaWath commented on 5-module/3-task/index.js
> +    currentOffset -= 500;
нельзя завязываться на 500 px, на разной ширине экрана, могут быть разные размеры слайдов. 

Поэтому надо двигать, на ширину слайда, а не `500px`

2024-02-11 23:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-12 20:33 UTC, SinimaWath approved these changes

2024-02-12 20:33 UTC, merged